# version: '2.4' #dcp-v2.29.7: the attribute `version` is obsolete, it will be ignored
services:
  deb11-pve:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-pve:v2501-deb11
    # entrypoint: /bin/bash /srv/local/libvirt/build/entry-prex11.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "sv status |grep -v '+ +++ ' && exit 1 || exit 0 "]
    shm_size: 1g
    hostname: x11-virter
    privileged: true
    network_mode: ${NETWORK_MODE:-bridge} #host bridge; non.host: avoid multi-inst-network-conflict
    working_dir: /srv/local/libvirt
    cgroup: host
    # profiles: [default] #dcp不带参:不会激活之
    ports:
      # - 8006:8006
      - 64022:64022
      - 64081:64081
      - 64089:64089
    environment:
      - VNC_OFFSET=64
      - START_SESSION=${DESK:-openbox-session} #startfluxbox openbox-session xfce4-session
      - L=zh_CN
      - TZ=Asia/Shanghai
      - SSH_PASS=${SSH_PASS:-headless}
      - VNC_PASS=${VNC_PASS:-headless}
      - VNC_PASS_RO=${VNC_PASS_RO:-View123}
    tmpfs:
      - /var/run
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /_ext:/_ext
      # - ./:/srv/local/libvirt
      # - ./data-x11ubtaio/var-lib-libvirt:/var/lib/libvirt
      # - ./data-x11ubtaio/var-run-libvirt:/var/run/libvirt
      # - ./data-x11ubtaio/etc-libvirt-qemu:/etc/libvirt/qemu
