ARG VER=11
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/x11-base:core-debian-${VER}
ARG TARGETPLATFORM
ARG VER=11

# ICON
# RUN apt.sh \
#   hicolor-icon-theme adwaita-icon-theme humanity-icon-theme; \
#   cd /usr/share/icons && rm -rf Humanity* ubuntu-mono* LoginIcons Tango; \
#   exit 0
# APP # LOCALE 15.0 MB 
RUN apt.sh \
  # tzdata locales \
  # sakura plank \
  dunst scrot \
  geany thunar ristretto engrampa ; \
  # test "24.04" != "${VER}" && apt.sh leafpad; \
  exit 0


# ohmybash
RUN \
  # dropbear supervisor 
  apt.sh git; \
  bash -c "$(wget https://gitee.com/g-system/oh-my-bash/raw/sam-custom/tools/install.sh -O -)"; \
  sed -i 's/OSH_THEME.*/OSH_THEME="axin"/g' /root/.bashrc; cat /root/.bashrc |grep axin; 

# ASBRU: 3586 kB (disk: 15.5 MB)
# # curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.deb.sh' | sudo -E bash
# RUN apt.sh gnupg;
# RUN echo 1;\
#   curl -k -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | distro=ubuntu version=22.04 codename=jammy sudo -E bash; \
#   apt.sh asbru-cm; rm -f /etc/apt/sources.list.d/asbru-cm-release.list; \
#     mv /opt/asbru /usr/local; rm -f /usr/bin/asbru-cm; ln -s /usr/local/asbru/asbru-cm /usr/bin/; \
#     cd /usr/share/icons/hicolor/scalable/apps; rm -f asbru-cm.svg; ln -s /usr/local/asbru/res/asbru-logo.svg ./asbru-cm.svg; \
#   dpkg -l |grep asbru && exit 0 || exit 1; 



ENV \
  TERM=xterm \
  SHELL=/bin/bash
  # TIMEZONE=Asia/Shanghai \
  # LANG=C.UTF-8 \

  
# ADD ./dot/ /root/
# COPY supervisord.conf /etc/supervisord.conf

# VOLUME ["/var/run/libvirt/", "/var/lib/libvirt"]
# ENTRYPOINT ["/sbin/tini","--"]
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
