ARG VER=11
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/x11-base:core-debian-${VER}
ARG TARGETPLATFORM
ARG VER=11

# ICON
# RUN apt.sh \
#   hicolor-icon-theme adwaita-icon-theme humanity-icon-theme; \
#   cd /usr/share/icons && rm -rf Humanity* ubuntu-mono* LoginIcons Tango; \
#   exit 0
# APP # LOCALE 15.0 MB 
RUN apt.sh \
  # tzdata locales \
  # sakura plank \
  dunst scrot \
  geany thunar ristretto engrampa ; \
  # test "24.04" != "${VER}" && apt.sh leafpad; \
  exit 0


# ohmybash
RUN \
  # dropbear supervisor 
  apt.sh git; \
  bash -c "$(wget https://gitee.com/g-system/oh-my-bash/raw/sam-custom/tools/install.sh -O -)"; \
  sed -i 's/OSH_THEME.*/OSH_THEME="axin"/g' /root/.bashrc; cat /root/.bashrc |grep axin; 

# ASBRU: 3586 kB (disk: 15.5 MB)
# # curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.deb.sh' | sudo -E bash
# RUN apt.sh gnupg;
# RUN echo 1;\
#   curl -k -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | distro=ubuntu version=22.04 codename=jammy sudo -E bash; \
#   apt.sh asbru-cm; rm -f /etc/apt/sources.list.d/asbru-cm-release.list; \
#     mv /opt/asbru /usr/local; rm -f /usr/bin/asbru-cm; ln -s /usr/local/asbru/asbru-cm /usr/bin/; \
#     cd /usr/share/icons/hicolor/scalable/apps; rm -f asbru-cm.svg; ln -s /usr/local/asbru/res/asbru-logo.svg ./asbru-cm.svg; \
#   dpkg -l |grep asbru && exit 0 || exit 1; 


##########

#install base pkg
RUN \
  apt.sh systemctl gnupg;
  # apt update && \
  # apt install wget  systemctl nano vim  curl gnupg  ca-certificates -y

# #arm64: use jiangcuo_proxmox_arm64 https://github.com/jiangcuo/Proxmox-Arm64
# RUN echo "deb https://mirrors.apqa.cn/proxmox/ pvearm  main">/etc/apt/sources.list.d/foxi.list && \
# curl -k -fSL  https://mirrors.apqa.cn/proxmox/gpg.key |apt-key add -

#x64: add proxmox repo
  # 0.336 curl: (77) error setting certificate verify locations:
  # 0.336   CAfile: /etc/ssl/cert.pem
  # 0.336   CApath: none
  # 0.337 gpg: no valid OpenPGP data found.
RUN \
  case ${VER} in \
  "7")   V2=wheezy    ;; \  
  "8")   V2=jessie    ;; \  
  "9")   V2=stretch   ;; \
  "10")  V2=buster    ;; \
  "11")  V2=bullseye  ;; \
  "12")  V2=bookworm  ;; \
  esac; \
  echo "deb http://mirrors.ustc.edu.cn/proxmox/debian/ ${V2} pve-no-subscription" >>/etc/apt/sources.list && \
  curl -k -fSL https://mirrors.ustc.edu.cn/proxmox/debian/proxmox-release-${V2}.gpg|apt-key add -; \
  exit 0

# gpgKey: --allow-unauthenticated
  #12 10.56 Need to get 352 MB of archives.
  #12 10.56 After this operation, 1768 MB of additional disk space will be used.
#intall proxmox-ve without recommends. ##x64:ifupdown2 will install failed but ok
# RUN \
#   # apt.sh proxmox-ve; \
#   # apt -y remove pve-kernel-5.15.158-2-pve; \
#   # exit 0
#   # 
#   #apt install --ignore-depends=pve-kernel-5.15.158-2-pve ##不支持的参数(by:dpkg)
#   apt update && \
#   DEBIAN_FRONTEND=noninteractiv apt -y -d --no-install-recommends --allow-unauthenticated install  proxmox-ve | tee /tmp/apt_ins_proxmox-ve.log; \
#   # apt clean; \
#   rm -rf /var/lib/apt/lists/*; 

# dpkg: dependency problems prevent configuration of pve-manager:
#   pve-manager depends on ifupdown2 (>= 2.0.1-1+pve8) | ifenslave (>= 2.6); however:
#    Package ifupdown2 is not configured yet.
#    Package ifenslave is not installed.
#ifupdown2[ERR; 237 kB] ifenslave [OK; 98.0 kB{ifenslave+ifupdown}] ##ifenslave装后: pve-manager无ifupdown2依赖项了,安装ok
RUN apt.sh ifenslave;
# RUN apt.sh ifupdown2;

# apt install --no-install-recommends 
RUN apt.sh pve-qemu-kvm;
RUN \
  # local.handIns: 直接通过的;
  mkdir -p /var/lib/pve-manager/apl-info/download.proxmox.com; \
  apt.sh pve-manager;
# RUN apt.sh proxmox-ve;
#  {initramfs-tools linux-base openssh-server}
#  {proxmox-archive-keyring proxmox-kernel-helper pve-firmware pve-kernel-5.15 pve-kernel-5.15.158-2-pve}


# x64 only
  #repacked proxmox-ve; 7.2-1 >> 7.4-1
  RUN exit 0; export ver=7.4-1; \
  wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/proxmox-ve_${ver}_all.deb && \
  mkdir /tmp/pve && \
  dpkg -X proxmox-ve_${ver}_all.deb /tmp/pve/ && \
  dpkg -e proxmox-ve_${ver}_all.deb /tmp/pve/DEBIAN && \
  sed -i "s/pve-kernel-helper,//g" /tmp/pve/DEBIAN/control && \
  sed -i "s/pve-kernel-5.15,//g" /tmp/pve/DEBIAN/control && \
  dpkg-deb -Zxz  -b /tmp/pve/ /tmp/; \
  #repacked pve-manager; 7.2-7>> 7.4-20
  export ver=7.4-20; \
  wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/pve-manager_${ver}_amd64.deb && \
  mkdir /tmp/pve-manager && \
  dpkg -X pve-manager_${ver}_amd64.deb  /tmp/pve-manager/ && \
  dpkg -e pve-manager_${ver}_amd64.deb /tmp/pve-manager/DEBIAN && \
  sed -i "s/ifupdown2 (>= 2.0.1-1+pve8) | ifenslave (>= 2.6),//g" /tmp/pve-manager/DEBIAN/control && \
  dpkg-deb -Zxz  -b /tmp/pve-manager/ /tmp; \
  rm -rf /*.deb;
  ##install again
  RUN \
  # cp: cannot stat '/usr/share/doc/pve-manager/aplinfo.dat': No such file or directory
  mkdir -p /var/lib/pve-manager/apl-info/download.proxmox.com; \
  dpkg -i /tmp/*.deb || echo ok; \
  exit 0;

#set passwd for root
RUN echo "root:root"|chpasswd; \
  # web: can\t open '/etc/ssh/ssh_host_rsa_key.pub' - No such file or directory (500)
  mkdir -p /etc/ssh; touch /etc/ssh/ssh_host_rsa_key.pub;

# #clean
# RUN rm -rf /var/lib/apt/lists/*  /*.deb

#use setup.sh to start proxmox service
STOPSIGNAL SIGINT
CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]


ENV \
  TERM=xterm \
  SHELL=/bin/bash
  # TIMEZONE=Asia/Shanghai \
  # LANG=C.UTF-8 \

  
# ADD ./dot/ /root/
# COPY supervisord.conf /etc/supervisord.conf

# VOLUME ["/var/run/libvirt/", "/var/lib/libvirt"]
# ENTRYPOINT ["/sbin/tini","--"]
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
