ARG VER=11
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/x11-base:core-debian-${VER}
ARG TARGETPLATFORM
ARG VER=11

# ICON
# RUN apt.sh \
#   hicolor-icon-theme adwaita-icon-theme humanity-icon-theme; \
#   cd /usr/share/icons && rm -rf Humanity* ubuntu-mono* LoginIcons Tango; \
#   exit 0
# APP # LOCALE 15.0 MB 
RUN apt.sh \
  # tzdata locales \
  # sakura plank \
  dunst scrot \
  geany thunar ristretto engrampa ; \
  # test "24.04" != "${VER}" && apt.sh leafpad; \
  exit 0


# ohmybash
RUN \
  # dropbear supervisor 
  apt.sh git; \
  bash -c "$(wget https://gitee.com/g-system/oh-my-bash/raw/sam-custom/tools/install.sh -O -)"; \
  sed -i 's/OSH_THEME.*/OSH_THEME="axin"/g' /root/.bashrc; cat /root/.bashrc |grep axin; 

# ASBRU: 3586 kB (disk: 15.5 MB)
# # curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.deb.sh' | sudo -E bash
# RUN apt.sh gnupg;
# RUN echo 1;\
#   curl -k -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | distro=ubuntu version=22.04 codename=jammy sudo -E bash; \
#   apt.sh asbru-cm; rm -f /etc/apt/sources.list.d/asbru-cm-release.list; \
#     mv /opt/asbru /usr/local; rm -f /usr/bin/asbru-cm; ln -s /usr/local/asbru/asbru-cm /usr/bin/; \
#     cd /usr/share/icons/hicolor/scalable/apps; rm -f asbru-cm.svg; ln -s /usr/local/asbru/res/asbru-logo.svg ./asbru-cm.svg; \
#   dpkg -l |grep asbru && exit 0 || exit 1; 


##########

#install base pkg
RUN apt-get update && \
apt-get install wget  systemctl nano vim  curl gnupg  ca-certificates -y

# #arm64: use jiangcuo_proxmox_arm64 https://github.com/jiangcuo/Proxmox-Arm64
# RUN echo "deb https://mirrors.apqa.cn/proxmox/ pvearm  main">/etc/apt/sources.list.d/foxi.list && \
# curl -L https://mirrors.apqa.cn/proxmox/gpg.key |apt-key add -
#x64: add proxmox repo
RUN echo "deb http://mirrors.ustc.edu.cn/proxmox/debian/ bullseye pve-no-subscription" >>/etc/apt/sources.list && \
curl https://mirrors.ustc.edu.cn/proxmox/debian/proxmox-release-bullseye.gpg|apt-key add -

#intall proxmox-ve without recommends. ##x64:ifupdown2 will install failed but ok
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractiv apt-get -y --no-install-recommends  install  proxmox-ve || echo ok

# x64 only
  #repacked proxmox-ve
  RUN wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/proxmox-ve_7.2-1_all.deb && \
  mkdir /tmp/pve && \
  dpkg -X proxmox-ve_7.2-1_all.deb /tmp/pve/ && \
  dpkg -e proxmox-ve_7.2-1_all.deb /tmp/pve/DEBIAN && \
  sed -i "s/pve-kernel-helper,//g" /tmp/pve/DEBIAN/control && \
  sed -i "s/pve-kernel-5.15,//g" /tmp/pve/DEBIAN/control && \
  dpkg-deb -Zxz  -b /tmp/pve/ /tmp/

  #repacked pve-manager
  RUN wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/pve-manager_7.2-7_amd64.deb && \
  mkdir /tmp/pve-manager && \
  dpkg -X pve-manager_7.2-7_amd64.deb  /tmp/pve-manager/ && \
  dpkg -e pve-manager_7.2-7_amd64.deb /tmp/pve-manager/DEBIAN && \
  sed -i "s/ifupdown2 (>= 2.0.1-1+pve8) | ifenslave (>= 2.6),//g" /tmp/pve-manager/DEBIAN/control && \
  dpkg-deb -Zxz  -b /tmp/pve-manager/ /tmp

  ##install again
  RUN dpkg -i /tmp/*.deb || echo ok

#set passwd for root
RUN echo "root:root"|chpasswd

#clean
RUN rm -rf /var/lib/apt/lists/*  /*.deb

#use setup.sh to start proxmox service
STOPSIGNAL SIGINT
CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]


ENV \
  TERM=xterm \
  SHELL=/bin/bash
  # TIMEZONE=Asia/Shanghai \
  # LANG=C.UTF-8 \

  
# ADD ./dot/ /root/
# COPY supervisord.conf /etc/supervisord.conf

# VOLUME ["/var/run/libvirt/", "/var/lib/libvirt"]
# ENTRYPOINT ["/sbin/tini","--"]
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
